version: '3'
services:
  mysql_server:
    image: mysql:latest
    container_name: go_eventsourcing_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "dbpass"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
      MYSQL_DATABASE: "eventsourcing"