// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package eventSourcing

import (
	"sync"
)

var (
	lockeventStoreMockload sync.RWMutex
	lockeventStoreMocksave sync.RWMutex
)

// eventStoreRepositoryMock is a mock implementation of eventStoreRepository.
//
//     func TestSomethingThatUseseventStore(t *testing.T) {
//
//         // make and configure a mocked eventStoreRepository
//         mockedeventStore := &eventStoreRepositoryMock{
//             loadFunc: func(ID string) (*domainMessages, error) {
// 	               panic("TODO: mock out the load method")
//             },
//             saveFunc: func(message *domainMessage) error {
// 	               panic("TODO: mock out the save method")
//             },
//         }
//
//         // TODO: use mockedeventStore in code that requires eventStoreRepository
//         //       and then make assertions.
//
//     }
type eventStoreRepositoryMock struct {
	// loadFunc mocks the load method.
	loadFunc func(ID string) (*domainMessages, error)

	// saveFunc mocks the save method.
	saveFunc func(message *domainMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// load holds details about calls to the load method.
		load []struct {
			// ID is the ID argument value.
			ID string
		}
		// save holds details about calls to the save method.
		save []struct {
			// Message is the message argument value.
			Message *domainMessage
		}
	}
}

// load calls loadFunc.
func (mock *eventStoreRepositoryMock) load(ID string) (*domainMessages, error) {
	if mock.loadFunc == nil {
		panic("moq: eventStoreRepositoryMock.loadFunc is nil but eventStoreRepository.load was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: ID,
	}
	lockeventStoreMockload.Lock()
	mock.calls.load = append(mock.calls.load, callInfo)
	lockeventStoreMockload.Unlock()
	return mock.loadFunc(ID)
}

// loadCalls gets all the calls that were made to load.
// Check the length with:
//     len(mockedeventStore.loadCalls())
func (mock *eventStoreRepositoryMock) loadCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockeventStoreMockload.RLock()
	calls = mock.calls.load
	lockeventStoreMockload.RUnlock()
	return calls
}

// save calls saveFunc.
func (mock *eventStoreRepositoryMock) save(message *domainMessage) error {
	if mock.saveFunc == nil {
		panic("moq: eventStoreRepositoryMock.saveFunc is nil but eventStoreRepository.save was just called")
	}
	callInfo := struct {
		Message *domainMessage
	}{
		Message: message,
	}
	lockeventStoreMocksave.Lock()
	mock.calls.save = append(mock.calls.save, callInfo)
	lockeventStoreMocksave.Unlock()
	return mock.saveFunc(message)
}

// saveCalls gets all the calls that were made to save.
// Check the length with:
//     len(mockedeventStore.saveCalls())
func (mock *eventStoreRepositoryMock) saveCalls() []struct {
	Message *domainMessage
} {
	var calls []struct {
		Message *domainMessage
	}
	lockeventStoreMocksave.RLock()
	calls = mock.calls.save
	lockeventStoreMocksave.RUnlock()
	return calls
}
